export const cities_en = [
    "Berovo",
    "Bitola",
    "Bogdanci",
    "Debar",
    "Delčevo",
    "Demir Hisar",
    "Gevgelija",
    "Gostivar",
    "Kavadarci",
    "Kičevo",
    "Kočani",
    "Kratovo",
    "Kriva Palanka",
    "Kruševo",
    "Kumanovo",
    "Makedonska Kamenica",
    "Makedonski Brod",
    "Negotino",
    "Ohrid",
    "Pehčevo",
    "Prilep",
    "Probištip",
    "Radoviš",
    "Resen",
    "Sveti Nikole",
    "Štip",
    "Skopje",
    "Struga",
    "Strumica",
    "Tetovo",
    "Valandovo",
    "Veles",
    "Vinica"
];